const SUPABASE_URL = 'https://tryqarhbhwverbrwbwjy.supabase.co'
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyeXFhcmhiaHd2ZXJicndid2p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjk2ODQ0NzUsImV4cCI6MjA0NTI2MDQ3NX0.9mcH2QodPLNHK1fPiKUMTcSNufNDnFts1pXp0I5BF0o'

module.exports = {SUPABASE_URL, SUPABASE_KEY}